### ISSUE TITLE
next/image doesn't load with js disabled

### ISSUE THREAD

**Issue by ismay** [ismay/superwolff#93]
See:

- https://github.com/vercel/next.js/discussions/22048
- https://github.com/vercel/next.js/issues/21214
- https://github.com/vercel/next.js/issues/19223

Potential solutions:

- Using https://nextjs.org/docs/api-reference/next/image#loading with eager should fix this, but will load too much when js is enabled.
- It works natively in most browsers: https://web.dev/browser-level-image-lazy-loading, so either they're not using the native implementation (which seems to be the case), or their placeholder logic is at fault

**Comment by ismay** [comment]
Could also measure the image size with js with the available next/image cb. Would mean I could get rid of the rather complex sizes calculations. But it would also mean that when next/image starts working without js my responsive images wouldn't work without js, plus it might load incorrect image sizes before measuring.

**Comment by ismay** [comment]
Works now

**Comment by vamshi9666** [comment]
@ismay What did you do to get it working ?

**Comment by ismay** [comment]
It's a while ago, but I believe that next.js fixed this. So if you're on a recent version this should just work automatically.

**Comment by solonik1** [comment]
Hi, @ismay Were you able to fix the error? If yes, how did you do it?
